import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { getModuleColor, MODULE_POTENTIAL_SHADES } from '../src/lib/moduleColors.ts'

const outputUrl = new URL('../docs/module-colors/examples/palette.svg', import.meta.url)
const rows = [
  { label: '未装備', detail: 'null', type: null },
  { label: 'MOD-X', detail: 'X', type: 'X' },
  { label: 'MOD-Y', detail: 'Y', type: 'Y' },
  { label: 'MOD-Δ', detail: 'D / Δ', type: 'Δ' },
  { label: 'MOD-α', detail: 'A / α', type: 'α' },
  { label: 'MOD-β', detail: 'B / β', type: 'β' },
  { label: '不明', detail: 'unknown', type: undefined },
]
const columns = [
  { label: '基準色', detail: '潜在を省略', potential: undefined },
  ...MODULE_POTENTIAL_SHADES.map((_, index) => ({
    label: `潜在${index + 1}`,
    detail: index === 0 ? '明るい' : index === MODULE_POTENTIAL_SHADES.length - 1 ? '暗い' : '',
    potential: index + 1,
  })),
]
const margin = 40
const labelsWidth = 136
const columnWidth = 126
const rowHeight = 88
const gridTop = 184
const width = margin * 2 + labelsWidth + columnWidth * columns.length
const height = gridTop + rowHeight * rows.length + 76

const escapeXml = (value) => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')

const text = (x, y, value, className, extra = '') =>
  `<text x="${x}" y="${y}" class="${className}" ${extra}>${escapeXml(value)}</text>`

const svg = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/generateModuleColorExample.mjs. Do not edit directly. -->',
  `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title description">`,
  '<title id="title">MOD共通配色：基準色と潜在別の色見本</title>',
  '<desc id="description">未装備、MOD-X、MOD-Y、MOD-Δ、MOD-α、MOD-β、不明について、基準色と潜在1から6の色を表示する。潜在1から6へ向かって明るい色から暗い色になる。</desc>',
  '<style>',
  'text { font-family: "Yu Gothic", YuGothic, "Hiragino Kaku Gothic ProN", system-ui, sans-serif; fill: #283341; }',
  '.title { font-size: 27px; font-weight: 700; }',
  '.subtitle { font-size: 14px; fill: #586472; }',
  '.heading, .row-label { font-size: 16px; font-weight: 700; }',
  '.detail { font-size: 12px; fill: #687381; }',
  '.hex { font-family: ui-monospace, Consolas, monospace; font-size: 13px; fill: #445160; }',
  '</style>',
  `<rect width="${width}" height="${height}" fill="#ffffff"/>`,
  text(margin, 54, 'MOD共通配色', 'title'),
  text(margin, 84, '種類で色を決め、潜在1 → 6で明るい色から暗い色へ。', 'subtitle'),
  text(margin, 108, '同じ種類・潜在なら、MODレベルや表示順によらず同じ色。', 'subtitle'),
]

for (const [index, column] of columns.entries()) {
  const centerX = margin + labelsWidth + columnWidth * (index + 0.5)
  svg.push(text(centerX, 148, column.label, 'heading', 'text-anchor="middle"'))
  if (column.detail) svg.push(text(centerX, 169, column.detail, 'detail', 'text-anchor="middle"'))
}

for (const [index, row] of rows.entries()) {
  const y = gridTop + rowHeight * index
  svg.push(`<path d="M${margin} ${y}H${width - margin}" stroke="#e5e9ee"/>`)
  svg.push(text(margin, y + 34, row.label, 'row-label'))
  svg.push(text(margin, y + 58, row.detail, 'detail'))

  for (const [columnIndex, column] of columns.entries()) {
    const x = margin + labelsWidth + columnWidth * columnIndex + 10
    const color = getModuleColor(row.type, column.potential)
    svg.push(`<rect x="${x}" y="${y + 12}" width="${columnWidth - 20}" height="40" rx="6" fill="${color}"/>`)
    svg.push(text(x + (columnWidth - 20) / 2, y + 72, color, 'hex', 'text-anchor="middle"'))
  }
}

const gridBottom = gridTop + rowHeight * rows.length
svg.push(`<path d="M${margin} ${gridBottom}H${width - margin}" stroke="#e5e9ee"/>`)
svg.push(text(margin, gridBottom + 32, '未装備は null のみ。空文字・undefined・未知の種類は「不明」。', 'subtitle'))
svg.push(text(margin, gridBottom + 55, '生成元: src/lib/moduleColors.ts', 'detail'))
svg.push('</svg>', '')

await mkdir(new URL('.', outputUrl), { recursive: true })
await writeFile(outputUrl, svg.join('\n'), 'utf8')
console.log(`Generated ${fileURLToPath(outputUrl)}`)
